// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLHr3MQGavw064D06WU0CH7TRCOONTGJ8',
    appId: '1:533245095161:web:76bd872fe10ba4f6974628',
    messagingSenderId: '533245095161',
    projectId: 'cses-8569f',
    authDomain: 'cses-8569f.firebaseapp.com',
    storageBucket: 'cses-8569f.firebasestorage.app',
    measurementId: 'G-PQ9VSD90JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHIKPHVUkaGJStReTe1D_bMczVDDWXq5I',
    appId: '1:533245095161:android:c4a903a2912fa70d974628',
    messagingSenderId: '533245095161',
    projectId: 'cses-8569f',
    storageBucket: 'cses-8569f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeH35elGy6jrpCL1HuuwhJ9ZV_U2zh1U8',
    appId: '1:533245095161:ios:beebe639bf3b3f6d974628',
    messagingSenderId: '533245095161',
    projectId: 'cses-8569f',
    storageBucket: 'cses-8569f.firebasestorage.app',
    iosBundleId: 'com.example.cses2Fashionstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeH35elGy6jrpCL1HuuwhJ9ZV_U2zh1U8',
    appId: '1:533245095161:ios:beebe639bf3b3f6d974628',
    messagingSenderId: '533245095161',
    projectId: 'cses-8569f',
    storageBucket: 'cses-8569f.firebasestorage.app',
    iosBundleId: 'com.example.cses2Fashionstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLHr3MQGavw064D06WU0CH7TRCOONTGJ8',
    appId: '1:533245095161:web:e09b451973e9ac5c974628',
    messagingSenderId: '533245095161',
    projectId: 'cses-8569f',
    authDomain: 'cses-8569f.firebaseapp.com',
    storageBucket: 'cses-8569f.firebasestorage.app',
    measurementId: 'G-1RLLKWPED1',
  );
}
